// GENERATED by tools/gen_sprites.py — do not edit by hand.
// Re-run: python3 tools/gen_sprites.py
//
// Sprites are character matrices; PixelPalette.charToColor maps each
// character to a C64 colour. '.' is transparent.

/// Pixel-art sprite matrices, drawn with light outlines because every
/// screen in the app sits on a dark background.
class PixelSprites {
  const PixelSprites._();

  /// 23x14
  static const List<String> bicycle = <String>[
    '.......................',
    '.......................',
    '.............llllll....',
    '.......WWW.....l.......',
    '........llllllll.......',
    '....llll.l....lllll....',
    '..ll...lll...llll..ll..',
    '..l...l.l.l..ll.l...l..',
    '.l....l..ll.ll...l...l.',
    '.l...Wllllll.l...W...l.',
    '.l.......l...l.......l.',
    '..l.....l.....l.....l..',
    '..ll...ll.....ll...ll..',
    '....lll.........lll....',
  ];

  /// 23x14
  static const List<String> moto = <String>[
    '.......................',
    '.......................',
    '...............lllll...',
    '....llllllllllll.......',
    '....lllllyyyyyll.......',
    '....lllllllllllllll....',
    '..ll..lrrrrrrrlll..ll..',
    '..l.ddlrrrrrrrl.dld.l..',
    '.l.dddllllllllllddld.l.',
    '.l.ddddd.l...l.dlldd.l.',
    '.l.ddddd.l...l.ddddd.l.',
    '..l.ddd.l.....l.ddd.l..',
    '..ll...ll.....ll...ll..',
    '....lll.........lll....',
  ];

  /// 20x12
  static const List<String> car = <String>[
    '....................',
    '....lllllllllll.....',
    '....lcccclccccl.....',
    '....lcccclccccl.....',
    '.llllllllllllllllll.',
    '.lrrrrrrrrrrrrrrrrl.',
    '.yRRRRRRRRRRRRRRRRR.',
    '.lRRlllRRRRRRlllRRl.',
    '.lllldlllllllldllll.',
    '...ldddl....ldddl...',
    '...l.d.l....l.d.l...',
    '....lll......lll....',
  ];

  /// 44x17
  static const List<String> ship = <String>[
    '............................................',
    '............WWWWW.......WWWWW...............',
    '............WrrrW.......WrrrW...............',
    '............WrrrW.......WrrrW...............',
    '.....WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.......',
    '.....WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.......',
    '.....WWWbbWbbWbbWbbWbbWbbWbbWbbWbbWWWWWWW...',
    '.....WWWbbWbbWbbWbbWbbWbbWbbWbbWbbWWWWccW...',
    '.....WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWccW...',
    '.....WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW...',
    '.W.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW...',
    '..WWrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr...',
    '...rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr...',
    '...rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr...',
    '...rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr...',
    '......nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn......',
    '............................................',
  ];

  /// 13x15
  static const List<String> cone = <String>[
    '.............',
    '.............',
    '......K......',
    '.....KRK.....',
    '.....KRK.....',
    '....KRRRK....',
    '....KWWWK....',
    '...KWWWWWK...',
    '...KRRRRRK...',
    '..KRRRRRRRK..',
    '..KWWWWWWWK..',
    '.KWWWWWWWWWK.',
    '.KRRRRRRRRRK.',
    'KdddddddddddK',
    'KKKKKKKKKKKKK',
  ];

  /// 16x5
  static const List<String> water = <String>[
    'bbBccbbbbbBccbbb',
    'BBbbbBBbBBbbbBBb',
    'bbbbbbbBbbbbbbbB',
    'bBBBbbbbbBBBbbbb',
    'bbbbbbBbbbbbbbBb',
  ];
}
