// GENERATED by tools/gen_sprites.py — do not edit by hand.
// Re-run: python3 tools/gen_sprites.py
//
// Sprites are character matrices indexed into `palette` below.
// '.' is transparent.

import 'dart:ui' show Color;

/// Pixel-art sprite matrices and the palette they index into.
class PixelSprites {
  const PixelSprites._();

  /// Character -> colour. Generated with the sprites so the two cannot
  /// drift: a sprite using an unmapped character would render nothing.
  static const Map<String, Color> palette = <String, Color>{
    'K': Color(0xFF000000),
    'W': Color(0xFFFFFFFF),
    'r': Color(0xFF68372B),
    'R': Color(0xFF9A6759),
    'c': Color(0xFF70A4B2),
    'p': Color(0xFF6F3D86),
    'g': Color(0xFF588D43),
    'G': Color(0xFF9AD284),
    'b': Color(0xFF352879),
    'B': Color(0xFF6C5EB5),
    'y': Color(0xFFB8C76F),
    'o': Color(0xFF6F4F25),
    'n': Color(0xFF433900),
    'd': Color(0xFF444444),
    'm': Color(0xFF6C6C6C),
    'l': Color(0xFF959595),
    '1': Color(0xFFF2C9A0),
    '2': Color(0xFFFDC293),
    '3': Color(0xFF954D2B),
    '4': Color(0xFFE8B48E),
    '5': Color(0xFF5A301D),
    '6': Color(0xFFE29937),
    '7': Color(0xFFA4411B),
    '8': Color(0xFF2A2320),
    'A': Color(0xFF2A5C9E),
    'P': Color(0xFFEA7289),
    'V': Color(0xFF8B5CAE),
    'T': Color(0xFF4AB1AB),
    'Y': Color(0xFFF3B62F),
    'E': Color(0xFF4E9E4A),
    'F': Color(0xFFF2ECE6),
    'J': Color(0xFF36506E),
    'N': Color(0xFF3A3F52),
    'O': Color(0xFFC86A2C),
  };

  /// 11x15
  static const List<String> walkBlue0 = <String>[
    '....555....',
    '....555....',
    '....511....',
    '...AAAAA...',
    '...AAdAA...',
    '....AdA....',
    '....AdA....',
    '....AdA....',
    '....ANd....',
    '...1.dNd...',
    '.....dN....',
    '.....dN....',
    '....ddN....',
    '...d...N...',
    '..ddd.FFF..',
  ];

  /// 11x15
  static const List<String> walkBlue1 = <String>[
    '....555....',
    '....555....',
    '....511....',
    '...AAAAA...',
    '...AAdAA...',
    '....AAd....',
    '....AAd....',
    '...AAAAd...',
    '...ANNNd...',
    '...1.dNd...',
    '....d.NN...',
    '....d.NN...',
    '...d...NN..',
    '...d...N...',
    '..ddd.FFF..',
  ];

  /// 11x15
  static const List<String> walkBlue2 = <String>[
    '....555....',
    '....555....',
    '....511....',
    '...AAAAA...',
    '...AAdAA...',
    '....AdA....',
    '....AdA....',
    '....AdA....',
    '....dNA....',
    '...d.dN1...',
    '.....dN....',
    '.....dN....',
    '....Ndd....',
    '...N...d...',
    '..FFF.ddd..',
  ];

  /// 11x15
  static const List<String> walkBlue3 = <String>[
    '....555....',
    '....555....',
    '....511....',
    '...AAAAA...',
    '...AAdAA...',
    '....dAA....',
    '....dAA....',
    '...dAAAA...',
    '...dNNNA...',
    '...d.dN1...',
    '....NNd....',
    '....NNd....',
    '...NN..d...',
    '...N...d...',
    '..FFF.ddd..',
  ];

  /// 11x15
  static const List<String> walkPink0 = <String>[
    '....666....',
    '....666....',
    '....622....',
    '...PPPPP...',
    '...PPdPP...',
    '....PdP....',
    '....PdP....',
    '....PdP....',
    '....PNd....',
    '...2.dNd...',
    '.....dN....',
    '.....dN....',
    '....ddN....',
    '...d...N...',
    '..ddd.PPP..',
  ];

  /// 11x15
  static const List<String> walkPink1 = <String>[
    '....666....',
    '....666....',
    '....622....',
    '...PPPPP...',
    '...PPdPP...',
    '....PPd....',
    '....PPd....',
    '...PPPPd...',
    '...PNNNd...',
    '...2.dNd...',
    '....d.NN...',
    '....d.NN...',
    '...d...NN..',
    '...d...N...',
    '..ddd.PPP..',
  ];

  /// 11x15
  static const List<String> walkPink2 = <String>[
    '....666....',
    '....666....',
    '....622....',
    '...PPPPP...',
    '...PPdPP...',
    '....PdP....',
    '....PdP....',
    '....PdP....',
    '....dNP....',
    '...d.dN2...',
    '.....dN....',
    '.....dN....',
    '....Ndd....',
    '...N...d...',
    '..PPP.ddd..',
  ];

  /// 11x15
  static const List<String> walkPink3 = <String>[
    '....666....',
    '....666....',
    '....622....',
    '...PPPPP...',
    '...PPdPP...',
    '....dPP....',
    '....dPP....',
    '...dPPPP...',
    '...dNNNP...',
    '...d.dN2...',
    '....NNd....',
    '....NNd....',
    '...NN..d...',
    '...N...d...',
    '..PPP.ddd..',
  ];

  /// 11x15
  static const List<String> walkGreen0 = <String>[
    '....888....',
    '....888....',
    '....833....',
    '...EEEEE...',
    '...EEdEE...',
    '....EdE....',
    '....EdE....',
    '....EdE....',
    '....FJd....',
    '...3.dJd...',
    '.....dJ....',
    '.....dJ....',
    '....ddJ....',
    '...d...J...',
    '..ddd.FFF..',
  ];

  /// 11x15
  static const List<String> walkGreen1 = <String>[
    '....888....',
    '....888....',
    '....833....',
    '...EEEEE...',
    '...EEdEE...',
    '....FEd....',
    '....FEd....',
    '...FEEEd...',
    '...FJJJd...',
    '...3.dJd...',
    '....d.JJ...',
    '....d.JJ...',
    '...d...JJ..',
    '...d...J...',
    '..ddd.FFF..',
  ];

  /// 11x15
  static const List<String> walkGreen2 = <String>[
    '....888....',
    '....888....',
    '....833....',
    '...EEEEE...',
    '...EEdEE...',
    '....EdE....',
    '....EdE....',
    '....EdE....',
    '....dJF....',
    '...d.dJ3...',
    '.....dJ....',
    '.....dJ....',
    '....Jdd....',
    '...J...d...',
    '..FFF.ddd..',
  ];

  /// 11x15
  static const List<String> walkGreen3 = <String>[
    '....888....',
    '....888....',
    '....833....',
    '...EEEEE...',
    '...EEdEE...',
    '....dEF....',
    '....dEF....',
    '...dEEEF...',
    '...dJJJF...',
    '...d.dJ3...',
    '....JJd....',
    '....JJd....',
    '...JJ..d...',
    '...J...d...',
    '..FFF.ddd..',
  ];

  /// 11x15
  static const List<String> walkPurple0 = <String>[
    '....555....',
    '....555....',
    '....522....',
    '...VVVVV...',
    '...VVdVV...',
    '....VdV....',
    '....VdV....',
    '....VdV....',
    '....VNd....',
    '...2.dNd...',
    '.....dN....',
    '.....dN....',
    '....ddN....',
    '...d...N...',
    '..ddd.FFF..',
  ];

  /// 11x15
  static const List<String> walkPurple1 = <String>[
    '....555....',
    '....555....',
    '....522....',
    '...VVVVV...',
    '...VVdVV...',
    '....VVd....',
    '....VVd....',
    '...VVVVd...',
    '...VNNNd...',
    '...2.dNd...',
    '....d.NN...',
    '....d.NN...',
    '...d...NN..',
    '...d...N...',
    '..ddd.FFF..',
  ];

  /// 11x15
  static const List<String> walkPurple2 = <String>[
    '....555....',
    '....555....',
    '....522....',
    '...VVVVV...',
    '...VVdVV...',
    '....VdV....',
    '....VdV....',
    '....VdV....',
    '....dNV....',
    '...d.dN2...',
    '.....dN....',
    '.....dN....',
    '....Ndd....',
    '...N...d...',
    '..FFF.ddd..',
  ];

  /// 11x15
  static const List<String> walkPurple3 = <String>[
    '....555....',
    '....555....',
    '....522....',
    '...VVVVV...',
    '...VVdVV...',
    '....dVV....',
    '....dVV....',
    '...dVVVV...',
    '...dNNNV...',
    '...d.dN2...',
    '....NNd....',
    '....NNd....',
    '...NN..d...',
    '...N...d...',
    '..FFF.ddd..',
  ];

  /// 11x15
  static const List<String> walkYellow0 = <String>[
    '....777....',
    '....777....',
    '....744....',
    '...YYYYY...',
    '...YYdYY...',
    '....YdY....',
    '....YdY....',
    '....YdY....',
    '....YJd....',
    '...4.dJd...',
    '.....dJ....',
    '.....dJ....',
    '....ddJ....',
    '...d...J...',
    '..ddd.YYY..',
  ];

  /// 11x15
  static const List<String> walkYellow1 = <String>[
    '....777....',
    '....777....',
    '....744....',
    '...YYYYY...',
    '...YYdYY...',
    '....YYd....',
    '....YYd....',
    '...YYYYd...',
    '...YJJJd...',
    '...4.dJd...',
    '....d.JJ...',
    '....d.JJ...',
    '...d...JJ..',
    '...d...J...',
    '..ddd.YYY..',
  ];

  /// 11x15
  static const List<String> walkYellow2 = <String>[
    '....777....',
    '....777....',
    '....744....',
    '...YYYYY...',
    '...YYdYY...',
    '....YdY....',
    '....YdY....',
    '....YdY....',
    '....dJY....',
    '...d.dJ4...',
    '.....dJ....',
    '.....dJ....',
    '....Jdd....',
    '...J...d...',
    '..YYY.ddd..',
  ];

  /// 11x15
  static const List<String> walkYellow3 = <String>[
    '....777....',
    '....777....',
    '....744....',
    '...YYYYY...',
    '...YYdYY...',
    '....dYY....',
    '....dYY....',
    '...dYYYY...',
    '...dJJJY...',
    '...d.dJ4...',
    '....JJd....',
    '....JJd....',
    '...JJ..d...',
    '...J...d...',
    '..YYY.ddd..',
  ];

  /// 11x15
  static const List<String> walkTeal0 = <String>[
    '....888....',
    '....888....',
    '....844....',
    '...TTTTT...',
    '...TTdTT...',
    '....TdT....',
    '....TdT....',
    '....TdT....',
    '....TNd....',
    '...4.dNd...',
    '.....dN....',
    '.....dN....',
    '....ddN....',
    '...d...N...',
    '..ddd.FFF..',
  ];

  /// 11x15
  static const List<String> walkTeal1 = <String>[
    '....888....',
    '....888....',
    '....844....',
    '...TTTTT...',
    '...TTdTT...',
    '....TTd....',
    '....TTd....',
    '...TTTTd...',
    '...TNNNd...',
    '...4.dNd...',
    '....d.NN...',
    '....d.NN...',
    '...d...NN..',
    '...d...N...',
    '..ddd.FFF..',
  ];

  /// 11x15
  static const List<String> walkTeal2 = <String>[
    '....888....',
    '....888....',
    '....844....',
    '...TTTTT...',
    '...TTdTT...',
    '....TdT....',
    '....TdT....',
    '....TdT....',
    '....dNT....',
    '...d.dN4...',
    '.....dN....',
    '.....dN....',
    '....Ndd....',
    '...N...d...',
    '..FFF.ddd..',
  ];

  /// 11x15
  static const List<String> walkTeal3 = <String>[
    '....888....',
    '....888....',
    '....844....',
    '...TTTTT...',
    '...TTdTT...',
    '....dTT....',
    '....dTT....',
    '...dTTTT...',
    '...dNNNT...',
    '...d.dN4...',
    '....NNd....',
    '....NNd....',
    '...NN..d...',
    '...N...d...',
    '..FFF.ddd..',
  ];

  /// 17x16
  static const List<String> cyclist0 = <String>[
    '.................',
    '.........66......',
    '.........62......',
    '.........PP......',
    '........PPP......',
    '.......PP..Pll...',
    '.....ldP..OOO....',
    '......dNOO.OO....',
    '......OdN..OO....',
    '...mmO.d.NOmOm...',
    '..m..Omd.Nm.O.m..',
    '.m..O.dmOON.O..m.',
    '.m..OOdOOmN.O..m.',
    '.m.....m.m.....m.',
    '..m...m...m...m..',
    '...mmm.....mmm...',
  ];

  /// 17x16
  static const List<String> cyclist1 = <String>[
    '.................',
    '.........66......',
    '.........62......',
    '.........PP......',
    '........PPP......',
    '.......PP..Pll...',
    '.....ldP..OOO....',
    '......NdOO.OO....',
    '......ONd..OO....',
    '...mmO.N.dOmOm...',
    '..m..OmN.dm.O.m..',
    '.m..O.NmOOd.O..m.',
    '.m..OONOOmd.O..m.',
    '.m.....m.m.....m.',
    '..m...m...m...m..',
    '...mmm.....mmm...',
  ];

  /// 18x15
  static const List<String> moto0 = <String>[
    '..................',
    '.........88.......',
    '.........81.......',
    '.........AA.......',
    '.......AAAmm......',
    '......AA...lml....',
    '...lllml..........',
    '...lllmlrr.l......',
    '...mlrrmrrlllmm...',
    '..m.lllmlllll..m..',
    '.m..llllmlll.l..m.',
    '.m.mmm.m..m.mmm.m.',
    '.m..m..m..m..m..m.',
    '..m...m....m...m..',
    '...mmm......mmm...',
  ];

  /// 18x15
  static const List<String> moto1 = <String>[
    '..................',
    '.........88.......',
    '.........81.......',
    '.........AA.......',
    '.......AAAmm......',
    '......AA...lml....',
    '...lllml..........',
    '...lllmlrr.l......',
    '...mlrrmrrlllmm...',
    '..m.lllmlllll..m..',
    '.m..llllmlll.l..m.',
    '.m.mmm.m..m.mmm.m.',
    '.m..m..m..m..m..m.',
    '..m...m....m...m..',
    '...mmm......mmm...',
  ];

  /// 36x13
  static const List<String> car0 = <String>[
    '....................................',
    '..........llllllllllllllll..........',
    '..........lcccccclcccccccl..........',
    '..........lcccccclcccccccl..........',
    '..........lcccccclcccccccl..........',
    '.llllllllllllllllllllllllllllllllll.',
    '.lrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrl.',
    '.yrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.',
    '.lrrrrrlllrrrrrrrrrrrrrrrrlllrrrrrl.',
    '.mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm.',
    '......l..ml..............l..ml......',
    '......l...l..............l...l......',
    '.......lll................lll.......',
  ];

  /// 36x13
  static const List<String> car1 = <String>[
    '....................................',
    '..........llllllllllllllll..........',
    '..........lcccccclcccccccl..........',
    '..........lcccccclcccccccl..........',
    '..........lcccccclcccccccl..........',
    '.llllllllllllllllllllllllllllllllll.',
    '.lrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrl.',
    '.yrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.',
    '.lrrrrrlllrrrrrrrrrrrrrrrrlllrrrrrl.',
    '.mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm.',
    '......lm..l..............lm..l......',
    '......l...l..............l...l......',
    '.......lll................lll.......',
  ];

  /// 58x20
  static const List<String> ship = <String>[
    '..........................................................',
    '................WWWWW.........WWWWW.......................',
    '................WrrrW.........WrrrW.......................',
    '................WrrrW.........WrrrW.......................',
    '................WrrrW.........WrrrW.......................',
    '......WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.........',
    '......WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.........',
    '......WWWbbWbbWbbWbbWbbWbbWbbWbbWbbWbbWbbWbbWWWWWWWWWWW...',
    '......WWWbbWbbWbbWbbWbbWbbWbbWbbWbbWbbWbbWbbWWWWWWccccW...',
    '......WWWbbWbbWbbWbbWbbWbbWbbWbbWbbWbbWbbWbbWWWWWWccccW...',
    '......WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWccccW...',
    '......WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW...',
    '.WW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW..',
    '...WWrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr..',
    '....rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr..',
    '....rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr..',
    '....rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr..',
    '....rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr..',
    '.......nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn.....',
    '..........................................................',
  ];

  /// 7x9
  static const List<String> cone = <String>[
    '.......',
    '.......',
    '...K...',
    '..KRK..',
    '..KWK..',
    '.KRRRK.',
    '.KWWWK.',
    'KdddddK',
    'KKKKKKK',
  ];

  /// 16x5
  static const List<String> water = <String>[
    'bbBccbbbbbBccbbb',
    'BBbbbBBbBBbbbBBb',
    'bbbbbbbBbbbbbbbB',
    'bBBBbbbbbBBBbbbb',
    'bbbbbbBbbbbbbbBb',
  ];
}
